# -*- coding: utf-8 -*-
"""CAB213PROJECT kritika.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pL_SnSr4X3ezedVszU-tKvovTf-Gc-UR

# **Flower Image Classification**

*   Submitted by: Kritika Sharma
*   Roll No.: 30
*   Registeration No.: 12404593
*   Section: D2411 Group:1
*   Course Code: CAB 213
*   Course Name: Applied AI- Computer Vision And Natural Language Processing

Stage 1: Problem Definition

The goal of this project is to build an image classification model that can identify different categories of flowers using deep learning. Instead of training a CNN from scratch, we use Transfer Learning with a pretrained MobileNetV2 model to achieve high accuracy with limited data and computational resources.
The objective is to classify images into 5 flower classes using the tf_flowers dataset and evaluate the performance using industry-standard metrics.
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models
import numpy as np

"""Stage 2: Dataset Collection

We use the TensorFlow Datasets library, which provides the tf_flowers dataset.
The dataset contains labeled images of flowers across multiple classes:
*   Daisy
*   Dandelion
*   Sunflowers
*   Roses
*   Tulips

TensorFlow Datasets automatically handles downloading, loading, and preparing the data, making it easy to integrate into Google Colab.
"""

print("Loading dataset...")
(ds_train, ds_test), ds_info = tfds.load(
    "tf_flowers",
    split=["train[:80%]", "train[80%:]"],
    shuffle_files=True,
    as_supervised=True,
    with_info=True
)

num_classes = ds_info.features["label"].num_classes
class_names = ds_info.features["label"].names
print("Classes:", class_names)

"""Stage 3: Preprocessing

Preprocessing ensures that images are clean and consistent before being fed into the model. The following steps were applied:

Resizing:
All images were resized to 224 × 224 pixels, which is the input size required for MobileNetV2.

Normalization:
Pixel values were scaled to a 0–1 range by dividing by 255.0 to speed up training and stabilize gradients.

Batching:
Data was batched into 32 images per batch for efficient GPU processing.

Shuffling & Prefetching:
TensorFlow’s AUTOTUNE pipeline was used to optimize loading speed and reduce bottlenecks.
"""

IMG_SIZE = 224

def preprocess(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = image / 255.0
    return image, label

batch_size = 32

train_ds = ds_train.map(preprocess).batch(batch_size).prefetch(tf.data.AUTOTUNE)
test_ds = ds_test.map(preprocess).batch(batch_size).prefetch(tf.data.AUTOTUNE)

"""Stage 4: Model Selection

We used MobileNetV2, a lightweight, high-performance CNN pretrained on ImageNet.
This allows the model to use previously learned image features (edges, textures, shapes) and adapt them to flower classification.

Steps involved:

Load the pretrained MobileNetV2 model without its top classification layer.

Freeze the pretrained layers so they don’t update during training.

Add custom layers:

Global Average Pooling

Dropout (to reduce overfitting)

Dense layer with softmax for flower class prediction

Train only the new layers on the flower dataset.

This gives high accuracy in less time and avoids overfitting.
"""

base_model = tf.keras.applications.MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights="imagenet"
)

base_model.trainable = False

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3),
    layers.Dense(num_classes, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# Step 5: Train Model
history = model.fit(
    train_ds,
    epochs=10,
    validation_data=test_ds
)

"""Stage 5: Evaluation and Testing

The trained model was evaluated on the test dataset to measure its performance.

We generated:

Accuracy

Loss curves

Predictions on sample images

The model was able to classify flower images with strong accuracy due to transfer learning.
"""

plt.figure(figsize=(14,6))

plt.subplot(1, 2, 1)
plt.plot(history.history["accuracy"], label="Train Acc")
plt.plot(history.history["val_accuracy"], label="Val Acc")
plt.legend()
plt.title("Accuracy")

plt.subplot(1, 2, 2)
plt.plot(history.history["loss"], label="Train Loss")
plt.plot(history.history["val_loss"], label="Val Loss")
plt.legend()
plt.title("Loss")

plt.show()

test_loss, test_acc = model.evaluate(test_ds)
print("Test Accuracy:", test_acc)

for images, labels in test_ds.take(1):
    sample_img = images[0]
    sample_label = labels[0]

    pred = model.predict(sample_img[None, ...])
    pred_class = np.argmax(pred)

    plt.imshow(sample_img)
    plt.title(f"Predicted: {class_names[pred_class]}\nTrue: {class_names[sample_label]}")
    plt.axis("off")
    plt.show()

